// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.devProblems;

public interface AuthorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.devProblems.Author)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 author_id = 1;</code>
   */
  int getAuthorId();

  /**
   * <code>optional string first_name = 2;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>optional string first_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>optional string last_name = 3;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>optional string last_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>optional string gender = 4;</code>
   */
  java.lang.String getGender();
  /**
   * <code>optional string gender = 4;</code>
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>optional int32 book_id = 5;</code>
   */
  int getBookId();
}
