// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.devProblems;

public interface BookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.devProblems.Book)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 book_id = 1;</code>
   */
  int getBookId();

  /**
   * <code>optional string title = 2;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>optional string title = 2;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>optional float price = 3;</code>
   */
  float getPrice();

  /**
   * <code>optional int32 pages = 4;</code>
   */
  int getPages();

  /**
   * <code>optional int32 author_id = 5;</code>
   */
  int getAuthorId();
}
